language: ruby
sudo: false
cache: bundler
before_install:
  - travis_retry gem update --system || travis_retry gem update --system 2.7.8
  - travis_retry gem install bundler --no-document || travis_retry gem install bundler --no-document -v 1.17.3
before_script:
  - gem update --system
script: ./script/ci
rvm:
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6.0
  - jruby-9.1.9.0
  - ruby-head
  - jruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: jruby-9.1.9.0

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/fde2367248d53de4fe70
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start:   never   # options: [always|never|change] default: always
